version: '3.3'
services:
  typebot-db:
    image: 'postgres:16'
    restart: always
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    image: 'baptistearno/typebot-builder:latest'
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '4001:3000'
    environment:
      - ENCRYPTION_SECRET=do+UspMmB/rewbX2K/rskFmtgGSSZ8Ta
      - 'DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot'
      - 'NEXTAUTH_URL=https://typebot.bastosdev.info'
      - 'NEXT_PUBLIC_VIEWER_URL=https://bot.bastosdev.info'
      - ADMIN_EMAIL=vinicius.bastos@me.com
      - DEBUG=true
      - DISABLE_SIGNUP=false
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USERNAME=vinnibastos@gmail.com
      - SMTP_PASSWORD=MPT4wfSWYrC2
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - GITHUB_CLIENT_ID=Ov23lit1gapIn46SH79e
      - GITHUB_CLIENT_SECRET=593042246dc1b1308231b5a5734cfceeb87e6a11
  typebot-viewer:
    image: 'baptistearno/typebot-viewer:latest'
    depends_on:
      - typebot-db
    restart: always
    ports:
      - '4002:3000'
    environment:
      - ENCRYPTION_SECRET=do+UspMmB/rewbX2K/rskFmtgGSSZ8Ta
      - 'DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot'
      - 'NEXTAUTH_URL=https://typebot.bastosdev.info'
      - 'NEXT_PUBLIC_VIEWER_URL=https://bot.bastosdev.info'
      - ADMIN_EMAIL=vinicius.bastos@me.com
      - DEBUG=true
      - DISABLE_SIGNUP=false
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USERNAME=vinnibastos@gmail.com
      - SMTP_PASSWORD=MPT4wfSWYrC2
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - GITHUB_CLIENT_ID=Ov23lit1gapIn46SH79e
      - GITHUB_CLIENT_SECRET=593042246dc1b1308231b5a5734cfceeb87e6a11
